const Router = require('koa-router')
const router = new Router({prefix:'/users'})
const {create,remove,update,find,findById,login,listFollowing,follow,unFollow,listFollowers} = require('../controllers/users.js')
const auth = require('../utils/auth.js')

router.post('/login', login)
router.post('/', create)
router.delete('/:id', auth,remove)
router.put('/:id', auth,update)
router.get('/:id', findById)
router.get('/', find)
router.get('/:id/following',listFollowing)
router.put('/following/:id',auth,follow)
router.delete('/following/:id',auth,unFollow)
router.get('/:id/followers',listFollowers)
module.exports = router